   const skills = [
    "JavaScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "PHP",
    "Ruby",
    "Go",
    "Rust",
    "Swift",
    "Kotlin",
    "TypeScript",
    "Scala",
    "Perl",
    "R",
    "MATLAB",
    "C",
    "Dart",
    "Elixir",
    "Haskell",
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Gatsby",
    "Ember.js",
    "jQuery",
    "Bootstrap",
    "Tailwind CSS",
    "Material-UI",
    "Ant Design",
    "Chakra UI",
    "Semantic UI",
    "Bulma",
    "Foundation",
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "FastAPI",
    "Spring Boot",
    "Spring Framework",
    "Ruby on Rails",
    "Laravel",
    "Symfony",
    "ASP.NET",
    "ASP.NET Core",
    ".NET Framework",
    "Gin",
    "Echo",
    "Koa.js",
    "Nest.js",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "Oracle",
    "SQL Server",
    "MariaDB",
    "Cassandra",
    "DynamoDB",
    "Firebase Firestore",
    "CouchDB",
    "Neo4j",
    "InfluxDB",
    "Elasticsearch",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Firebase",
    "Heroku",
    "DigitalOcean",
    "Netlify",
    "Vercel",
    "Cloudflare",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "Travis CI",
    "CircleCI",
    "Terraform",
    "Ansible",
    "Chef",
    "Puppet",
    "Nginx",
    "Apache",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "HTML5",
    "CSS3",
    "Sass",
    "Less",
    "PostCSS",
    "Webpack",
    "Vite",
    "Parcel",
    "Rollup",
    "Gulp",
    "npm",
    "Yarn",
    "REST API",
    "GraphQL",
    "SOAP",
    "gRPC",
    "WebSocket",
    "Socket.io",
    "OAuth",
    "JWT",
    "SAML",
    "Machine Learning",
    "Deep Learning",
    "Neural Networks",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "OpenCV",
    "NLTK",
    "spaCy",
    "Computer Vision",
    "Natural Language Processing",
    "Data Science",
    "Data Analysis",
    "Statistics",
    "Data Visualization",
    "Business Intelligence",
    "ETL",
    "Big Data",
    "Hadoop",
    "Spark",
    "Kafka",
    "Tableau",
    "Power BI",
    "D3.js",
    "Chart.js",
    "Mobile Development",
    "iOS Development",
    "Android Development",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Unity",
    "Unreal Engine",
    "Game Development",
    "3D Modeling",
    "Blender",
    "Maya",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe After Effects",
    "Figma",
    "Sketch",
    "Adobe XD",
    "UI/UX Design",
    "User Research",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "Accessibility",
    "SEO",
    "Google Analytics",
    "Google Ads",
    "Facebook Ads",
    "Social Media Marketing",
    "Content Marketing",
    "Email Marketing",
    "CRM",
    "Salesforce",
    "HubSpot",
    "WordPress",
    "Shopify",
    "WooCommerce",
    "E-commerce",
    "Project Management",
    "Agile",
    "Scrum",
    "Kanban",
    "JIRA",
    "Trello",
    "Asana",
    "Slack",
    "Microsoft Teams",
    "Leadership",
    "Team Management",
    "Communication",
    "Problem Solving",
    "Critical Thinking",
    "Creativity",
    "Time Management",
    "Adaptability",
    "Collaboration",
    "Negotiation",
    "Public Speaking",
    "Presentation Skills",
    "Technical Writing",
    "Documentation",
    "Research",
    "Analysis",
    "Quality Assurance",
    "Testing",
    "Unit Testing",
    "Integration Testing",
    "Selenium",
    "Cypress",
    "Jest",
    "Mocha",
    "JUnit",
    "Pytest",
    "Postman",
    "Cybersecurity",
    "Network Security",
    "Penetration Testing",
    "Ethical Hacking",
    "Blockchain",
    "Bitcoin",
    "Ethereum",
    "Smart Contracts",
    "Solidity",
    "Networking",
    "TCP/IP",
    "DNS",
    "HTTP/HTTPS",
    "VPN",
    "Linux",
    "Windows Server",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "VS Code",
    "IntelliJ IDEA",
    "Eclipse",
    "Xcode",
    "Android Studio",
    "Visual Studio",
    "Finance",
    "Accounting",
    "Financial Analysis",
    "Budgeting",
    "Excel",
    "VBA",
    "SQL",
    "Database Design",
    "Data Modeling",
    "Microservices",
    "Serverless",
    "API Design",
    "Load Testing",
    "Monitoring",
    "Debugging",
    "Code Review",
    "Test-Driven Development",
    "Continuous Integration",
    "Version Control",
    "Design Patterns",
    "Clean Code",
    "Performance Optimization",
    "Caching",
    "Multithreading",
    "Algorithms",
    "Data Structures",
    "Object-Oriented Programming",
    "Functional Programming",
    "Regular Expressions",
    "Mathematics",
    "Linear Algebra",
    "Calculus",
    "Sales",
    "Customer Service",
    "Account Management",
    "Business Development",
    "Market Research",
    "Product Management",
    "Roadmap Planning",
    "A/B Testing",
    "User Stories",
    "Scrum Master",
    "Product Owner",
    "Stakeholder Management",
    "Requirements Gathering",
    "Process Improvement",
    "Six Sigma",
    "Lean Manufacturing",
    "Supply Chain Management",
    "Logistics",
    "Inventory Management",
    "Procurement",
    "Contract Negotiation",
    "Legal Compliance",
    "GDPR",
    "ISO Standards",
    "Quality Management",
    "Audit",
    "Training",
    "Mentoring",
    "Coaching",
    "Performance Management",
    "Recruiting",
    "Interviewing",
    "Onboarding",
    "HR Management",
    "Employee Relations",
    "Change Management",
    "Team Building",
    "Event Planning",
    "Budget Management",
    "Financial Reporting",
    "KPI Tracking",
    "Dashboard Creation",
    "Data Interpretation",
    "Forecasting",
    "Risk Management",
    "Crisis Management",
    "Information Security",
    "Policy Development",
    "Content Creation",
    "Copywriting",
    "Blog Writing",
    "Video Production",
    "Graphic Design",
    "Brand Strategy",
    "Customer Segmentation",
    "Customer Journey Mapping",
    "Conversion Optimization",
    "Web Design",
    "Responsive Design",
    "Mobile-First Design",
    "Performance Optimization",
    "Accessibility Standards",
    "Internationalization",
    "Localization",
    "Translation",
    "Scientific Research",
    "Experimental Design",
    "Data Collection",
    "Statistical Analysis",
    "SPSS",
    "R Programming",
    "Python for Data Science",
    "Jupyter Notebooks",
    "Data Cleaning",
    "Feature Engineering",
    "Model Selection",
    "Cross-Validation",
    "Regression Analysis",
    "Classification",
    "Clustering",
    "Time Series Analysis",
    "Forecasting Models",
    "Anomaly Detection",
    "Recommendation Systems",
    "Sentiment Analysis",
    "Text Mining",
    "Image Processing",
    "Computer Graphics",
    "3D Animation",
    "Motion Graphics",
    "Video Editing",
    "Audio Editing",
    "Music Production",
    "Photography",
    "Digital Marketing",
    "PPC Advertising",
    "Display Advertising",
    "Affiliate Marketing",
    "Influencer Marketing",
    "Brand Management",
    "Public Relations",
    "Media Relations",
    "Crisis Communication",
    "Internal Communications",
    "Technical Support",
    "Help Desk",
    "Troubleshooting",
    "Network Administration",
    "System Administration",
    "Database Administration",
    "Cloud Architecture",
    "Solution Architecture",
    "Enterprise Architecture",
    "Security Architecture",
    "DevOps",
    "Site Reliability Engineering",
    "Infrastructure as Code",
    "Configuration Management",
    "Incident Response",
    "Disaster Recovery",
    "Business Continuity",
    "IT Service Management",
    "ITIL",
    "Service Desk",
    "Asset Management",
    "Vendor Management",
    "Procurement",
    "Contract Management",
    "Relationship Management",
    "Partnership Development",
    "Strategic Planning",
    "Business Strategy",
    "Competitive Analysis",
    "Market Analysis",
    "Industry Analysis",
    "Financial Modeling",
    "Valuation",
    "Investment Analysis",
    "Portfolio Management",
    "Risk Assessment",
    "Insurance",
    "Real Estate",
    "Property Management",
    "Construction Management",
    "Project Planning",
    "Resource Planning",
    "Schedule Management",
    "Cost Management",
    "Quality Control",
    "Safety Management",
    "Environmental Compliance",
    "Sustainability",
    "Green Technology",
    "Renewable Energy",
    "Energy Management",
    "Facility Management",
    "Operations Management",
    "Production Planning",
    "Manufacturing",
    "Quality Assurance",
    "Lean Six Sigma",
    "Statistical Process Control",
    "Root Cause Analysis",
    "Continuous Improvement",
    "Kaizen",
    "5S Methodology",
    "Value Stream Mapping",
    "Workflow Optimization",
    "Automation",
    "Robotics",
    "IoT",
    "Embedded Systems",
    "Firmware Development",
    "Hardware Design",
    "Circuit Design",
    "PCB Design",
    "Electronic Engineering",
    "Mechanical Engineering",
    "CAD Design",
    "AutoCAD",
    "SolidWorks",
    "Inventor",
    "Fusion 360",
    "Civil Engineering",
    "Structural Engineering",
    "Geotechnical Engineering",
    "Transportation Engineering",
    "Water Resources Engineering",
    "Environmental Engineering",
    "Chemical Engineering",
    "Process Engineering",
    "Biomedical Engineering",
    "Aerospace Engineering",
    "Materials Science",
    "Nanotechnology",
    "Biotechnology",
    "Pharmaceutical Development",
    "Clinical Research",
    "Regulatory Affairs",
    "Medical Writing",
    "Healthcare Administration",
    "Healthcare Analytics",
    "Electronic Health Records",
    "Telemedicine",
    "Health Information Management",
    "Medical Coding",
    "Healthcare Compliance",
    "Patient Safety",
    "Quality Improvement",
    "Nursing",
    "Patient Care",
    "Clinical Assessment",
    "Medication Administration",
    "Infection Control",
    "Emergency Response",
    "First Aid",
    "CPR",
    "Life Support",
    "Trauma Care",
    "Mental Health",
    "Counseling",
    "Therapy",
    "Psychology",
    "Behavioral Analysis",
    "Social Work",
    "Case Management",
    "Community Outreach",
    "Nonprofit Management",
    "Fundraising",
    "Grant Writing",
    "Volunteer Management",
    "Program Development",
    "Impact Measurement",
    "Social Impact",
    "Corporate Social Responsibility",
    "Sustainability Reporting",
    "ESG Reporting",
    "Stakeholder Engagement",
    "Community Relations",
    "Government Relations",
    "Public Policy",
    "Regulatory Analysis",
    "Legislative Research",
    "Policy Development",
    "Public Administration",
    "Urban Planning",
    "Regional Planning",
    "Land Use Planning",
    "Zoning",
    "Economic Development",
    "Tourism Management",
    "Hospitality Management",
    "Restaurant Management",
    "Food Service",
    "Culinary Arts",
    "Menu Planning",
    "Food Safety",
    "Nutrition",
    "Dietetics",
    "Fitness Training",
    "Personal Training",
    "Group Fitness",
    "Yoga Instruction",
    "Pilates",
    "Sports Coaching",
    "Athletic Training",
    "Sports Management",
    "Recreation Management",
    "Event Management",
    "Wedding Planning",
    "Conference Planning",
    "Trade Show Management",
    "Venue Management",
    "Catering Management",
    "Entertainment",
    "Music",
    "Performance",
    "Theater",
    "Film Production",
    "Television Production",
    "Broadcasting",
    "Journalism",
    "News Writing",
    "Feature Writing",
    "Investigative Reporting",
    "Editing",
    "Proofreading",
    "Publishing",
    "Book Publishing",
    "Magazine Publishing",
    "Digital Publishing",
    "Content Management",
    "Social Media Management",
    "Community Management",
    "Online Reputation Management",
    "Digital Strategy",
    "E-commerce Management",
    "Online Retail",
    "Marketplace Management",
    "Inventory Management",
    "Order Fulfillment",
    "Customer Support",
    "Live Chat Support",
    "Phone Support",
    "Email Support",
    "Knowledge Base Management",
    "Documentation",
    "Process Documentation",
    "User Manuals",
    "Training Materials",
    "Instructional Design",
    "E-learning Development",
    "Learning Management Systems",
    "Educational Technology",
    "Teaching",
    "Curriculum Development",
    "Lesson Planning",
    "Assessment Design",
    "Student Engagement",
    "Classroom Management",
    "Online Teaching",
    "Tutoring",
    "Academic Advising",
    "Student Services",
    "Admissions",
    "Financial Aid",
    "Career Services",
    "Alumni Relations",
    "Development",
    "Donor Relations",
    "Planned Giving",
    "Capital Campaigns",
    "Stewardship",
    "Database Management",
    "Data Entry",
    "Data Validation",
    "Data Migration",
    "Data Integration",
    "Data Warehousing",
    "Business Intelligence",
    "Reporting",
    "Analytics",
    "Metrics",
    "KPIs",
    "Benchmarking",
    "Performance Measurement",
    "Balanced Scorecard",
    "OKRs",
    "Goal Setting",
    "Strategic Thinking",
    "Innovation",
    "Design Thinking",
    "Lean Startup",
    "Entrepreneurship",
    "Business Planning",
    "Market Validation",
    "Customer Development",
    "Product-Market Fit",
    "Growth Hacking",
    "Scaling",
    "Operations",
    "Process Design",
    "Standard Operating Procedures",
    "Compliance",
    "Audit",
    "Internal Controls",
    "Risk Management",
    "Insurance",
    "Legal",
    "Contracts",
    "Intellectual Property",
    "Patents",
    "Trademarks",
    "Copyrights",
    "Licensing",
    "Mergers and Acquisitions",
    "Due Diligence",
    "Corporate Finance",
    "Investment Banking",
    "Private Equity",
    "Venture Capital",
    "Fundraising",
    "Investor Relations",
    "Financial Planning",
    "Wealth Management",
    "Retirement Planning",
    "Tax Planning",
    "Estate Planning",
    "Insurance Planning",
    "Financial Advisory",
    "Investment Advisory",
    "Portfolio Construction",
    "Asset Allocation",
    "Risk Tolerance Assessment",
    "Financial Education",
    "Credit Analysis",
    "Loan Underwriting",
    "Mortgage Lending",
    "Commercial Lending",
    "Trade Finance",
    "Foreign Exchange",
    "Derivatives",
    "Fixed Income",
    "Equity Research",
    "Investment Research",
    "Market Research",
    "Economic Research",
    "Industry Research",
    "Company Analysis",
    "Competitive Intelligence",
    "Business Intelligence",
    "Market Intelligence",
    "Trend Analysis",
    "Forecasting",
    "Scenario Planning",
    "Modeling",
    "Simulation",
    "Optimization",
    "Decision Analysis",
    "Problem Solving",
    "Critical Thinking",
    "Analytical Thinking",
    "Creative Problem Solving",
    "Innovation Management",
    "Change Management",
    "Organizational Development",
    "Culture Change",
    "Leadership Development",
    "Succession Planning",
    "Talent Management",
    "Performance Management",
    "Compensation",
    "Benefits",
    "Employee Engagement",
    "Retention",
    "Diversity and Inclusion",
    "Equal Opportunity",
    "Workplace Safety",
    "Occupational Health",
    "Ergonomics",
    "Industrial Hygiene",
    "Environmental Health",
    "Safety Training",
    "Emergency Preparedness",
    "Business Continuity Planning",
    "Disaster Recovery",
    "Crisis Management",
    "Communication",
    "Interpersonal Skills",
    "Relationship Building",
    "Networking",
    "Influence",
    "Persuasion",
    "Negotiation",
    "Conflict Resolution",
    "Mediation",
    "Facilitation",
    "Meeting Management",
    "Presentation Skills",
    "Public Speaking",
    "Writing",
    "Editing",
    "Research",
    "Information Literacy",
    "Data Literacy",
    "Digital Literacy",
    "Technology Skills",
    "Computer Skills",
    "Software Skills",
    "Hardware Skills",
    "Troubleshooting",
    "Technical Skills",
    "Mechanical Skills",
    "Manual Dexterity",
    "Attention to Detail",
    "Accuracy",
    "Precision",
    "Quality",
    "Reliability",
    "Consistency",
    "Efficiency",
    "Productivity",
    "Speed",
    "Agility",
    "Flexibility",
    "Adaptability",
    "Resilience",
    "Stress Management",
    "Emotional Intelligence",
    "Self-Awareness",
    "Self-Management",
    "Social Awareness",
    "Relationship Management",
    "Empathy",
    "Compassion",
    "Patience",
    "Persistence",
    "Determination",
    "Motivation",
    "Drive",
    "Ambition",
    "Initiative",
    "Proactivity",
    "Accountability",
    "Responsibility",
    "Integrity",
    "Ethics",
    "Professionalism",
    "Reliability",
    "Trustworthiness",
    "Honesty",
    "Transparency",
    "Authenticity",
    "Humility",
    "Respect",
    "Courtesy",
    "Diplomacy",
    "Tact",
    "Discretion",
    "Confidentiality",
    "Cultural Sensitivity",
    "Global Mindset",
    "Cross-Cultural Communication",
    "Language Skills",
    "Multilingual",
    "Interpretation",
    "Translation",
    "Localization",
    "International Business",
    "Global Markets",
    "Export/Import",
    "Supply Chain",
    "Logistics",
    "Distribution",
    "Warehousing",
    "Transportation",
    "Shipping",
    "Customs",
    "Trade Compliance",
    "International Law",
    "Trade Agreements",
    "Tariffs",
    "Foreign Exchange",
    "International Finance",
    "Cross-Border Payments",
    "Risk Management",
    "Political Risk",
    "Currency Risk",
    "Operational Risk",
    "Regulatory Risk",
    "Compliance Risk",
    "Reputational Risk",
    "Strategic Risk",
    "Financial Risk",
    "Market Risk",
    "Credit Risk",
    "Liquidity Risk",
    "Interest Rate Risk",
    "Inflation Risk",
    "Commodity Risk",
    "Technology Risk",
    "Cybersecurity Risk",
    "Data Privacy",
    "Information Security",
    "Network Security",
    "Application Security",
    "Cloud Security",
    "Mobile Security",
    "IoT Security",
    "Blockchain Security",
    "Cryptography",
    "Encryption",
    "Digital Forensics",
    "Incident Response",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Security Auditing",
    "Compliance",
    "Governance",
    "Risk Assessment",
    "Threat Intelligence",
    "Security Awareness",
    "Security Training",
    "Business Continuity",
    "Disaster Recovery",
    "Emergency Response",
    "Crisis Communication",
    "Reputation Management",
    "Stakeholder Management",
    "Investor Relations",
    "Media Relations",
    "Public Affairs",
    "Government Relations",
    "Regulatory Affairs",
    "Policy Analysis",
    "Advocacy",
    "Lobbying",
    "Public Policy",
    "Legislative Affairs",
    "Regulatory Compliance",
    "Industry Standards",
    "Best Practices",
    "Benchmarking",
    "Performance Improvement",
    "Process Optimization",
    "Efficiency",
    "Effectiveness",
    "Innovation",
    "Creativity",
    "Ideation",
    "Brainstorming",
    "Design Thinking",
    "Human-Centered Design",
    "User Experience",
    "User Interface",
    "Usability",
    "User Research",
    "User Testing",
    "Accessibility",
    "Inclusive Design",
    "Universal Design",
    "Design Systems",
    "Style Guides",
    "Brand Guidelines",
    "Visual Identity",
    "Logo Design",
    "Typography",
    "Color Theory",
    "Layout Design",
    "Composition",
    "Visual Hierarchy",
    "Information Architecture",
    "Navigation Design",
    "Interaction Design",
    "Motion Design",
    "Animation",
    "Microinteractions",
    "Prototyping",
    "Wireframing",
    "Mockups",
    "User Flows",
    "Journey Mapping",
    "Service Design",
    "Systems Design",
    "Design Strategy",
    "Design Research",
    "Design Validation",
    "Design Metrics",
    "Design Operations",
    "Design Leadership",
    "Design Management",
    "Creative Direction",
    "Art Direction",
    "Visual Communication",
    "Graphic Design",
    "Print Design",
    "Digital Design",
    "Web Design",
    "Mobile Design",
    "App Design",
    "Game Design",
    "Industrial Design",
    "Product Design",
    "Service Design",
    "Experience Design",
    "Environmental Design",
    "Interior Design",
    "Architecture",
    "Urban Design",
    "Landscape Design",
    "Fashion Design",
    "Textile Design",
    "Jewelry Design",
    "Furniture Design",
    "Lighting Design",
    "Set Design",
    "Costume Design",
    "Makeup Design",
    "Hair Design",
    "Nail Art",
    "Body Art",
    "Tattoo Design",
    "Illustration",
    "Digital Art",
    "Traditional Art",
    "Fine Art",
    "Painting",
    "Drawing",
    "Sculpture",
    "Ceramics",
    "Pottery",
    "Glassblowing",
    "Metalworking",
    "Woodworking",
    "Carpentry",
    "Furniture Making",
    "Cabinetry",
    "Upholstery",
    "Sewing",
    "Tailoring",
    "Pattern Making",
    "Knitting",
    "Crocheting",
    "Embroidery",
    "Quilting",
    "Weaving",
    "Dyeing",
    "Printing",
    "Screen Printing",
    "Block Printing",
    "Letterpress",
    "Bookbinding",
    "Papermaking",
    "Origami",
    "Calligraphy",
    "Hand Lettering",
    "Sign Making",
    "Mural Painting",
    "Fresco",
    "Mosaic",
    "Stained Glass",
    "Jewelry Making",
    "Beadwork",
    "Wire Wrapping",
    "Soldering",
    "Welding",
    "Blacksmithing",
    "Glasswork",
    "Leatherwork",
    "Bookbinding",
    "Restoration",
    "Conservation",
    "Antique Repair",
    "Art Restoration",
    "Furniture Restoration",
    "Vintage Clothing Restoration",
    "Automobile Restoration",
    "Motorcycle Restoration",
    "Boat Restoration",
    "Aircraft Restoration",
    "Electronics Repair",
    "Appliance Repair",
    "Computer Repair",
    "Mobile Device Repair",
    "Watch Repair",
    "Clock Repair",
    "Instrument Repair",
    "Piano Tuning",
    "Guitar Setup",
    "Violin Making",
    "Bow Making",
    "Reed Making",
    "Music Composition",
    "Songwriting",
    "Arranging",
    "Orchestration",
    "Music Theory",
    "Harmony",
    "Counterpoint",
    "Music Analysis",
    "Music Education",
    "Music Therapy",
    "Sound Engineering",
    "Audio Production",
    "Recording",
    "Mixing",
    "Mastering",
    "Live Sound",
    "Broadcast Audio",
    "Podcast Production",
    "Radio Production",
    "Voice Acting",
    "Narration",
    "Dubbing",
    "Subtitling",
    "Closed Captioning",
    "Sign Language Interpretation",
    "Braille Translation",
    "Assistive Technology",
    "Adaptive Equipment",
    "Rehabilitation",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Massage Therapy",
    "Chiropractic",
    "Acupuncture",
    "Yoga Therapy",
    "Meditation",
    "Mindfulness",
    "Stress Reduction",
    "Relaxation Techniques",
    "Breathing Exercises",
    "Tai Chi",
    "Qigong",
    "Martial Arts",
    "Self-Defense"
  ]

  export default skills